#Spencer Miller
#Final Project
#04/29/14

#                            Kingdom of Ashyria

import time, random
def intro():
    print('Elder: Hello, I have never seen you around here before.')
    time.sleep(2)
    print('Elder: What is your name?')
    name = input('Name: ')
    time.sleep(1)
    print('...')
    time.sleep(1)
    print('Elder: Good to meet you', name)
    time.sleep(2)
    print('Elder: Here in the kingdom of Ashyria we are in great danger from attacks.')
    time.sleep(2)
    print('Elder: There are three classes you may choose to use.')
    time.sleep(2)
    print('Elder: The Rogue, the Warrior and the Mage.')
    time.sleep(2)
    player()

def player():        
    print('Elder: Which class are you interested in using in your quest\n to save the kingdom?')
    time.sleep(2)
    player = input('[R]ogue, [W]arrior or [M]age: ')
    player = player.upper()
    if player[0] is 'R':
        rogueCombat1()
    elif player[0] is 'W':
        warriorCombat1()
    elif player[0] is 'M':
        mageCombat1()

def rogueCombat1():
    hp = 10
    print('> A wild beast jumps from the bushes and stands in an aggressive pose towards you!')
    time.sleep(3)
    print('> You find yourself in battle with the creature.')
    time.sleep(2)
    print('> The creature has 5 health and can damage you.')
    time.sleep(2)
    print('> Do you want to engage the creature? [Y]es or [N]o?')
    battle = input()
    battle = battle.upper()
    if battle[0] is 'Y':
        dmg1 = random.randint(1,5)
        endHp = hp - dmg1
        print('> Your hp is now', endHp)
        print('> The battle was won!')
        time.sleep(2)
        if dmg1 is 0:
            print('> Luckily for you, you made it out of there without a scratch.')
        elif dmg1 <= 1:
            print('> You take the furs of the beast and keep moving towards the city.')
    elif battle[0] is 'N':
        dmg2 = random.randint(1,5)
        hp1 = 10
        print('> You were attacked once you turned your back, damaging you for', dmg2)
        endHp1 = hp1 - dmg2
        print('> Your hp is down to', endHp1)
    time.sleep(2)
    print('...')
    time.sleep(2)
    body()

def warriorCombat1():
    print('> As you head to the city you stumble apon three thugs assaulting a caravan.')
    time.sleep(4)
    print('> They turn to you and find you have very nice armor and they want it.')
    time.sleep(4)
    print('> Each thug is weak yet have medium attack power.')
    time.sleep(2)
    print('> Do you want to engage the thugs? [Y]es or [N]o?')
    battle2 = input()
    battle2 = battle2.upper()
    if battle2[0] is 'Y':
        dmg = random.randint(0,5)
        hp = 10
        endHp = hp - dmg
        print('> Your hp is now', endHp)
        print('> The battle was won!')
        time.sleep(2)
        if dmg is 0:
            print('> Luckily for you, you made it out of there without a scratch.')
        elif dmg <= 1:
            print('> After a bloody battle you help the caravan reassemble and \nhead towards the city.')
    elif battle[0] is 'N':
        dmg1 = random.randint(1,5)
        hp1 = 10
        print('> You were attacked once you turned your back, damaging you for', dmg4)
        endHp = hp1 - dmg1
        print('> Your hp is down to', endHp)
    time.sleep(2)
    print('...')
    time.sleep(2)
    body()

def mageCombat1():
    print('> Moving to the city, you find yourself looking at a stone that has \na faint blue glow.')
    time.sleep(4)
    print('> You notice that the stop has a rune on it so you pick it up for a \n loser look.')
    time.sleep(4)
    print('> The stone turns hot and glows a bright red before exploding and \nsending you into a tree.')
    time.sleep(3)
    print('> A Lava Spite bursts out of the forest and stands before you.')
    time.sleep(2)
    print('> Do you want to battle the Lava Sprite? [Y]es or [N]o?')
    battle3 = input()
    battle3 = battle3.upper()
    if battle3[0] is 'Y':
        dmg = random.randint(0,3)
        hp = 10
        endHp = hp - dmg
        print('> Your hp is now', endHp)
        print('> The battle was won!')
        time.sleep(2)
        if dmg is 0:
            print('> Luckily for you, you made it out of there without a scratch.')
        elif dmg <= 1:
            print('> You are burned a little on your side but you are able to move on.')
    elif battle[0] is 'N':
        dmg = random.randint(1,3)
        hp1 = 10
        print('> You were attacked once you turned your back, damaging you for', dmg6)
        endHp = hp1 - dmg
        print('> Your hp is down to', endHp)
    time.sleep(2)
    print('...')
    time.sleep(2)
    body()
    
def body():
    print('> The city draws closer and you see the guards at the gate.')
    time.sleep(3)
    print('> The guard steps forward to confront you.')
    time.sleep(3)
    print('> Guard: State your business, wanderer!')
    time.sleep(3)
    print('...')
    time.sleep(2)
    print('Guard: Wait a second, you are the one everyone has been talking about arent ya?')
    time.sleep(4)
    print('Guard: Well... Come on in Chosen One, the queen is waiting for you.')
    time.sleep(3)
    print('\n')
    print('> The closer you get to the palace, the more beautiful it becomes.')
    time.sleep(3)
    print('> The walls are made of marble and engraved into them are pictures of the wars.')
    time.sleep(4)
    print('> You notice that the queen is portrayed as very noble and heroic in the beginning')
    time.sleep(4)
    print('> but as you get near the palace doors, the queen starts to look more and more weak.')
    time.sleep(4)
    print('> You make your way inside the palace and can see the beauty of it.')
    time.sleep(4)
    print('> The pillars lining the giant room are wrapped with bright gold and vines')
    time.sleep(4)
    print('and the floors feel warm underneath you with a faint green glow in between the cracks.')
    time.sleep(4)
    print('Queen: Ah, finally you have come to us...')
    time.sleep(2)
    print('Queen: I have seen you in my dreams, and have been waiting many years for your arrival.')
    time.sleep(3)
    print('Queen: You may be wondering why we have called you to our kingdom.')
    time.sleep(3)
    print('Queen: We have been at war with the Korygorn for as long as I can remember.')
    time.sleep(4)
    print('Queen: They are beings made from molten earth, set on ravaging the land for their lord.')
    time.sleep(4)
    print('Queen: ...The ruler of these monsters is known as Krawl.')
    time.sleep(3)
    print('Queen: You must set out to the core of their city and destroy him!')
    time.sleep(3)
    print('Queen: Then our people, as well as other nations across the Earth can live in peace...')
    time.sleep(2)
    print('Queen: ...once again.')
    time.sleep(2)
    print('The queen closes her eyes and exits the room without saying another word.')
    time.sleep(3)
    print('> You know what must be done. You must save Ashyria!')
    time.sleep(3)
    body2()
    
def body2():
    print('> You exit the city with a marked location of where Krawl is located')
    time.sleep(2)
    print('> He is located many journeys away. The path ahead is a very dangerous one.')
    time.sleep(3)
    print('> You quest begins!')
    time.sleep(2)
    print('\n')
    time.sleep(2)
    print('\n')
    print('> You are about to cross a cobblestone bridge over a murky stream')
    time.sleep(3)
    print('> You find yourself confronted by a nasty bridge troll who will not let you pass!')
    time.sleep(2)
    print('> The creature has 6 health and can damage you.')
    time.sleep(2)
    print('> Do you want to engage the creature? [Y]es or [N]o?')
    battle = input()
    battle = battle.upper()
    if battle[0] is 'Y':                                                                
        dmg1 = random.randint(0,6)
        hp = 10
        endHp = hp - dmg1
        print("> The troll begins to charge at you!")
        time.sleep(3)
        print("> As the troll sprints into striking range, it swings it's gnarled club!")
        time.sleep(3)
        print("> When the club passes over it's head, you strike out with your attack, impaling the troll!")
        time.sleep(4)
        if dmg1 is 0:
            print('> Luckily for you, the club fell behind the troll and did not hit you.')
        elif dmg1 <= 1:
            print('> As the troll dies, it uses its last strength and strikes you!')
        print('> Your hp is now', endHp)
        print('> The battle was won!') 
    elif battle[0] is 'N':
        dmg2 = random.randint(1,4)
        hp1 = 10
        print('> Trying to get past the troll it was able to swing at you, damaging you for', dmg2)
        endHp1 = hp1 - dmg2
        print('> Your hp is down to', endHp1)
    time.sleep(3)
    body3()
    
def body3():
    print('> After leaving the bridge a trail going off the path leads into an open field.')
    time.sleep(3)
    print('> The field has been scorched by flame! The earth is scarred and smoking beneath your feet...')
    time.sleep(2)
    print('> From a hole in the middle of the scorched land, a Flaming Legionary Cohort rises!')
    time.sleep(2)
    print('> The Soldier has 20 health and WILL damage you!')
    time.sleep(2)
    print('> Do you want to engage the creature? [Y]es or [N]o?')
    battle = input()
    battle = battle.upper()
    if battle[0] is 'Y':                                                                
        dmg1 = random.randint(3,6)
        hp = 10
        endHp = hp - dmg1
        print("> The flaming monster raises fire from cracks in the earth, scorching all that it touches!")
        time.sleep(3)
        print('> You leap forth to the monster, reaving its breatplate with a mighty blow!')
        time.sleep(1)
        print("> the monster screams in agony as a blue flame bursts from it's chest. The flame dies and the monster falls!")
        time.sleep(4)
        print('> Heat from the monster heats your armor until you begin to burn')
        time.sleep(3)
        print('> Your hp is now', endHp)
        print('> The battle was won!')
        time.sleep(2)
    elif battle[0] is 'N':
        dmg2 = random.randint(2,5)
        hp1 = 10
        print('> The flaming legionary sends forth fire, scorching you for', dmg2)
        endHp1 = hp1 - dmg2
        print('> Your hp is down to', endHp1)
    time.sleep(3)
    body4()

def body4():
    print('> You move through the field and figure out the the Cohort you have encountered ambushed dozens of')
    time.sleep(1)
    print('> Ashyrian soldiers doing a patrol.')
    time.sleep(3)
    print('> You notice that the patrol was headed towards the Baharia Mountains, so you head that way.')
    time.sleep(3)
    print('> Upon arriving at the foothills of a mountain, you hear the crumbling of stones')
    time.sleep(3)
    print('> You turn to see a charging Hell-Hound!')
    time.sleep(2)
    print('> The creature has 4 health and is faster than you.')
    time.sleep(2)
    print('> Do you want to engage the creature? [Y]es or [N]o?')
    battle = input()
    battle = battle.upper()
    if battle[0] is 'Y':                                                                
        dmg1 = random.randint(0,4)
        hp = 10
        endHp = hp - dmg1
        print("> The Hell Hound charges at you!")
        time.sleep(3)
        print("> The Hell Hound leaps in the air!")
        time.sleep(2)
        print("> At the last second, you duck, beacing your weapon so that it runs through the hounds' core!")
        time.sleep(4)
        if dmg1 is 0:
            print('> The hound dies while on your weapon, releasing a horrid howl before dying.')
        elif dmg1 <= 1:
            print("> As the hound dies it thrashes about, slashing you with its claws!")
        print('> Your hp is now', endHp)
        print('> The battle was won!') 
    elif battle[0] is 'N':
        dmg2 = random.randint(2,6)
        hp1 = 10
        print('> The hound lunges onto your back, damaging you for', dmg2)
        endHp1 = hp1 - dmg2
        print('> Your hp is down to', endHp1)
    time.sleep(3)
    body5()

def body5():
    print('> You find a cave in the rocks, which looks to be a great place to spend then night and continue the.')
    time.sleep(1)
    print(' journey tomorrow morning.')
    time.sleep(3)
    print('> While settling into your camp for the night, everything becomes silent and unusually warm')
    time.sleep(3)
    print('> In the trees south of your camp, a set of eight fiery red eyes are glaring at you!')
    time.sleep(2)
    print('> Suddenly the creature scatters towards you revealing itself in the bright light of the moon.')
    time.sleep(3)
    print('> Its an Ember Spider! Its poisen ignites blood throughout the body causing a horrible death.')
    time.sleep(3)
    print('> The creature has 4 health and is poisonous.')
    time.sleep(2)
    print('Do you want to engage the creature? [Y]es or [N]o?')
    battle = input()
    battle = battle.upper()
    if battle[0] is 'Y':                                                                
        dmg = random.randint(3,6)
        hp = 10
        endHp = hp - dmg
        print("> The spider darts on above you onto the rocky wall and shows its giant fangs!")
        time.sleep(3)
        print("> The Ember Spider crawls in a circle around you, timing when it will strike")
        time.sleep(2)
        if dmg is 3:
            print('> The spider attacks, striking with bare fangs!')
        elif dmg <= 4:
            print("> The spider attacks, striking with poisoned fangs!")
        print('> Your hp is now', endHp)
        print('> The battle was won!') 
    elif battle[0] is 'N':
        dmg2 = random.randint(0,6)
        hp1 = 10
        print('> The spider chases you, damaging you for', dmg2)
        endHp1 = hp1 - dmg2
        print('> Your hp is down to', endHp1)
    time.sleep(2)
    end()

def end():
    print('> Passing over the mountain, you are able to see Krawls city.')
    time.sleep(3)
    print('> You move closer to the city, the odor of burning flesh fills the air.')
    time.sleep(4)
    print('> The closer you get to the city the stronger the stench is, yet, it does not negate you from your quest.')
    time.sleep(4)
    print('> You are able to slip inside the gates unnoticed and make your way towards the core of the city.')
    time.sleep(4)
    print('> Thousands of molten creatures linger about as you move silently between armouries and dens.')
    time.sleep(4)
    print('> You are able to see the tower in which Krawl is located!')
    time.sleep(3)
    print('> Not seeing any creature in sight you make a dash towards the entrance.')
    time.sleep(3)
    print('> A Magma Hydra explodes out of the ground in front of you!')
    time.sleep(4)
    print('Hydra: You dare set foot on this land human!')
    time.sleep(4)
    print('Hydra: Hahaha! It is not possible for a creature like you to come this far and expect')
    time.sleep(5)
    print('to reach our great lord Krawl.')
    time.sleep(4)
    print('Hydra: I feel a bit of hunger for human flesh...')
    time.sleep(1)
    print("...So I'll just have to quench it with your bones!")
    time.sleep(3)
    print('> The creature has 30 health and is very dangerous.')
    time.sleep(3)
    print('> Do you want to engage the creature? [Y]es or [N]o?')
    battle = input()
    battle = battle.upper()
    if battle[0] is 'Y':                                                                
        dmg1 = random.randint(4,9)
        hp = 10
        endHp = hp - dmg1
        print("> The Hydra lets loose with a volley of lava and fire!")
        time.sleep(3)
        print("> You take shelter behind a large pile of dead of Ashyrian civilians!")
        time.sleep(3)
        print("> You begin to circle the Hydra as it releases more fire and lava...")
        time.sleep(3)
        print("> You move from object to object dodging oncomming projectiles.")
        time.sleep(3)
        print("> Making your way behind the creature you spot its magma core sticking out of its back!")
        time.sleep(4)
        print('> You launch your weapon towards the magma core and strike it.')
        time.sleep(4)
        print('> Nothing happens and the creature turns agressively towards you.')
        time.sleep(4)
        print('> Hydra: Haha! Your puny weapon does nothing to me!')
        time.sleep(4)
        print('> A light shines harshly from the back of the creature!')
        time.sleep(4)
        print('> You turn and duck as the Magma Hydra explodes tearing the entrance gate apart')
        time.sleep(4)
        print('> You wander to the entrance of a magnificent, decrepit tower')
        time.sleep(4)
        print('> There seems to be an imminent sense of danger and evil here...')
        time.sleep(4)
        print("> You begin to walk towards the throne room when a deafeneing bellow is heard!")
        time.sleep(4)
        print("> You turn into the room and Lord Krawl stands before you wielding glowing red cleavers.")
        time.sleep(4)
        print('> Lord Krawl has 100 health and is massive, fast, and extremely evil!')
        time.sleep(3)
        print("> Krawl flies over you, cutting you off from moving!")
        time.sleep(5)
        print("> Entering a state of rage and madness, the demon whirls about with the cleavers")
        time.sleep(4)
        print("> The demon seems to come into focus on you!")
        time.sleep(4)                   #'Murder Treason Death Fire' spelled backwards
        print("> Krawl mutters 'REDRUM NOSAERT HTAED ERIF' as it crashes about and slashes the air with the \n now flaming cleavers!")
        time.sleep(6)
        print("> As Krawl draws closer, your weapon begins to glow and vibrate rapidly!")
        time.sleep(4)
        print("> A light shines forth from your weapon, exposing an unseen inscription on the pommel")
        time.sleep(4)
        print("> The inscription reads 'To those who wield shall death obey'")
        time.sleep(4)
        print("> Krawl becomes even more enraged at the presence of your weapon")
        time.sleep(4)
        print("> Krawl launches forth directly at you! The searing blades wavering through super-heated space...")
        time.sleep(4)
        print("> You raise your weapon to parry the attack, and when the cleavers strike down onto you...")
        time.sleep(4)
        print("> An explosion of light and ice detonates from the point of impact, obliterating everything around you,")
        time.sleep(4)
        print('and sending you airborne and making you unconcious...')
        time.sleep(3)
        print("> You wake up, seeing your warm breath in the cold air.")
        time.sleep(4)
        print('> You lean up and realize you are laying in soft, pure white snow.')
        time.sleep(4)
        print('> The land around you is covered in a beautiful layer of snow and the sun softly shines over the landscape.')
        time.sleep(4)
        print('> You have saved the Kingdom of Ashyria, now you must return to the Queen, as she has more work to be done...')
        time.sleep(1)
        print('\n')
        time.sleep(1)
        print('\n')
        time.sleep(1)
        print('\n')
        time.sleep(1)
        print('\n')
        credit()
    elif battle[0] is 'N':
        dmg2 = random.randint(4,7)
        hp1 = 10
        print('> The Magma Hyrda breathes flame onto your back as you run through the gates, damaging you for', dmg2)
        endHp1 = hp1 - dmg2
        print('> Your hp is down to', endHp1)
        time.sleep(4)
        print('> You limp through the halls of the tower in search of Krawl.')
        time.sleep(4)
        print('> A trail of blood follows you as you have a great deal of pain coming from your shoulder.')
        time.sleep(4)
        print('> You turn to the throne room finding Krawl waiting with his weapons drawn.')
        time.sleep(4)
        print('Krawl: Looks like you were able to make it past my legion, human.')
        time.sleep(4)
        print('Krawl: You are far to weak to fight me, I wish to help you.')
        time.sleep(4)
        print('Krawl: I am going to make you my General in the Legion and together we will ravage this land!')
        time.sleep(4)
        print('> You raise your weapon towards Krawl, he flies to you in a second and grabs your arm!')
        time.sleep(4)
        print('Krawl: No no no... None of that human. Now you will obey me and you will kill every last human on this Earth!')
        time.sleep(5)
        print('> Searing pain shoots from your arm to the rest of your body, you feel your skin tearing apart as flames break out.')
        time.sleep(4)
        print('> Losing all memory from the past, you stand in front of Krawl in Molten General Armor and salute your new lord...')
        time.sleep(1)
        print('\n')
        time.sleep(1)
        print('\n')
        time.sleep(1)
        print('\n')
        time.sleep(1)
        print('\n')
        credit()

def credit():
    print('___Kingdom_of_Ashyria___')
    time.sleep(1)
    print('\n')
    time.sleep(1)
    print('\n')
    time.sleep(1)
    print('\n')
    time.sleep(1)
    print('\n')
    print('Created by:')
    time.sleep(1)
    print('\n')
    print('Spencer Miller')
    time.sleep(1)
    print('\n')
    time.sleep(1)
    print('\n')
    time.sleep(1)
    print('\n')
    print('Image credit to MachiavelliCro at http://machiavellicro.deviantart.com/art/Kingdom-of-Auri-309737677')
    
intro()
    
